$._questions = [
        ["What is the simplest thing you could do on your biggest problem?","@YvesHanoulle"],
        ["What did you observe that surprised you?","@gdinwiddie"],
        ["If you could change 1 thing today what would it be?","@YvesHanoulle"],
        ["What do you want to achieve this year?","@YvesHanoulle"],
        ["If you could preserve 1 thing today, what would it be? ","@JerryWeinberg"],
        ["What action that someone in your team did in the last year are you proud of?","@YvesHanoulle"],
        ["what does happiness mean in your team?","@YvesHanoulle"],
        ["What does being a team really mean (as opposed to the way the word is often misapplied) ","@gerrykirk"],
        ["What frustrates you most in your team? What is your part in it?","@YvesHanoulle"],
        ["What tool , idea, methodology have you been neglecting lately?","@YvesHanoulle"],
        ["Some people don't fit agile, how would you help them move on/out?","@mhsutton"],
        ["If Pippi Longstocking would be on your project, what would she do?","@YvesHanoulle"],
        ["do you know what your team/organisation values? what is it?","@mhsutton"],
        ["How have you improved yourself in the last month?","@mhsutton"],
        ["How good is your team (are you) doing on sustainanble pace. How could you improve it?","@YvesHanoulle"],
        ["How could you gain back the energy you had for your project when you first started?","@YvesHanoulle"],
        ["What is the worst thing you could do on your project and why?","@YvesHanoulle"],
        ["if you brough in your most critical customer, what would he say?","@YvesHanoulle"],
        ["What is the toughest question nobody askes?","@YvesHanoulle"],
        ["what is for you the hardest part of the agile practises and why?","@YvesHanoulle"],
        ["When was the last time you asked for help? On what occasions did you not ask help, when you should have?","@YvesHanoulle"],
        ["What have you learned this week?","@YvesHanoulle"],
        ["Who is your hero, what would he or she says if he was on your project?","@YvesHanoulle"],
        ["Look around. What do you NOT see?","@gdinwiddie"],
        ["What is one thing you're ready /now/ to change? Not the biggest thing, perhaps, but something meaningful.","@gdinwiddie"],
        ["Try to explain your biggest problem to a 3 year old. How would she solve it?","@YvesHanoulle"],
        ["Should a coach have practical experience of all the key responsibilities they coach? why or why not?","@mhsutton"],
        ["What Do You Do When You Don’t Know What To Do?","@YvesHanoulle"],
        ["whose presence would help your 'stuck' conversation move into action?","@deborahh"],
        ["What did you learn from your last failure?","@YvesHanoulle"],
        ["If pair programming is possible, how can you make pair testing possible too?","@didierkoc"],
        ["When was the last time you said authentically thank you. ","@YvesHanoulle"],
        ["How is TDD defining your product? ","@didierkoc"],
        ["Is there an entirely different way to deliver what you deliver?","@PaulSloane"],
        ["What key assets do you bring to your work?","@YvesHanoulle"],
        ["What is a more powerful question than the one I was about to ask?","@gdinwiddie"],
        [" What can we do so that change won't happen ?","@ToF_"],
        ["When do you know its time to leave as coach?","@martinheider"],
        ["How are you going to show you're Done?","@JohnMcFadyen"],
        ["Cape Horn is known as major milestone on the clippers route.  Where is your Cape Horn?","@didierkoc"],
        ["What is the worst thing that can happen to your project?","@YvesHanoulle"],
        ["How much time have you focus today on adding pure value?","@YvesHanoulle"],
        ["What do we know that ain't so ?","@ToF_"],
        ["How do you know your coach is helping you?","@didierkoc"],
        ["When was the last time you've walked in the shoes of others?","@martinheider"],
        ["Have you ever been significantly impeded by bad code? Why did you write it? ","@unclebobmartin"],
        ["What do you hope to achieve today?","@JohnMcFadyen"],
        ["What would you have done 20 years ago?","@YvesHanoulle"],
        ["What do you still want to learn?","@martinheider"],
        ["What would you do if it was your first day?","@YvesHanoulle"],
        ["Is it all about your colleague in the next hole near you or someone 1000 miles away?","@didierkoc"],
        ["What is the vision of your team? What do they want to be known as?","@JohnMcFadyen"],
        ["When you change your process (with the intention of improving it) how do you know you actually got any better?","@OlafLewitz"],
        ["How long took your team to stabilize after you adapted #agile?","@didierkoc"],
        ["How could you make your own product obsolete?","@YvesHanoulle"],
        ["Doing something excellent take 10000hrs. How many sprints is it?","@didierkoc"],
        ["What other ways could you split that story down?","@JohnMcFadyen"],
        ["Does your company have a smile machine?","@YvesHanoulle"],
        ["Have you observed in your environment something like a depression because of #Scrum ?","@didierkoc"],
        ["What would you do if it was your last day?","@YvesHanoulle"],
        ["Where stays your ego during a team work?","@didierkoc"],
        ["Which value needs your attention today?","@JohnMcFadyen"],
        ["When you could make one wish, what would it be?","@YvesHanoulle"],
        ["Why would you use story points instead of hours?","@didierkoc"],
        ["What do you do to take feedback more seriously?","@YvesHanoulle"],
        ["What do you want to be known for? How can you achieve that?","@JohnMcFadyen"],
        ["How does your work of today increase your product's value to the customer or user?","@OlafLewitz"],
        ["Why are  customers talking  to you?","@didierkoc"],
        ["What risk are you taking today and what value do you hope to increase by that?","@OlafLewitz"],
        ["How are budgets hurting your company","@YvesHanoulle"],
        ["What would be the advantage of doing agile without stories?","@didierkoc"],
        ["Who could get you out of your comfort zone?","@YvesHanoulle"],
        ["When did you ask for help for the last time ?","@ToF_"],
        ["Why do you read #arotd?","@didierkoc"],
        ["When did you last change someone's opinion with a good question?","@OlafLewitz"],
        ["What would Steve Jobs do?","@YvesHanoulle"],
        ["How much would you pay for your product?","@didierkoc"],
        ["How can you improve yourself next week?","@JohnMcFadyen"],
        ["How can you make things worse?","@YvesHanoulle"],
        ["How can you make your team more effective and which first step are you going to take today?","@OlafLewitz"],
        ["How do you make time for deliberate practice? ","@JohnMcFadyen"],
        ["What is your WIP limit?","@YvesHanoulle"],
        ["Consider your coworkers. What appreciation can you give them today?","@gdinwiddie"],
        ["When IT WILL be possible NOT IMPOSSIBLE?","@didierkoc"],
        ["What is a reason to be satisfied, then stop and not improve?","@didierkoc"],
        ["What would Freud do?","@YvesHanoulle"],
        ["How to stay motivated while sprinting all the time?","@didierkoc"],
        ["When was the last time you pushed an idea to the extreme? What happened out there?","@JohnMcFadyen"],
        ["Which change could you introduce to your life today to make your work/life balance more sustainable?","@OlafLewitz"],
        ["What would you do if you were in a startup/Multinational?","@YvesHanoulle"],
        ["How are you really different?","@didierkoc"],
        ["What can't you do now? How can you make it possible?","@JohnMcFadyen"],
        ["What will keep your team doing craft?","@didierkoc"],
        ["Imagine your team stays together for 10 year, what keeps you together?","@YvesHanoulle"],
        ["When you defer a decision, how do you notice the last responsible moment has come?","@OlafLewitz"],
        ["What are your personal signals for being balanced?","@martinheider"],
        ["Can people in the team explain why they should follow the process?","@JohnMcFadyen"],
        ["How do you achieve autonomy, mastery and purpose in what you do?","@OlafLewitz"],
        ["What could you change about how you work to help the team?","@JohnMcFadyen"],
        ["Did I hear what the other person intended or what I expected to hear?","@gdinwiddie"],
        ["How do you keep everyone on the team knowing about the main purpose of everyone else on the team?","@OlafLewitz"],
        ["Are you aware of what is the business value what you're working on?","@JohnMcFadyen"],
        ["What can you do better tomorrow than you did today?","@gdinwiddie"],
        ["When you experience deepness of abyss described Ms. Satir's organization change model, what will you do?","@didierkoc"],
        ["How much do the team trust each other? How can you improve this?","@JohnMcFadyen"],
        ["What words are not accepted in your team?","@YvesHanoulle"],
        ["Why do you believe in Agile development? What does it give you?","@JohnMcFadyen"],
        ["What is he most common emotion in your team?","@YvesHanoulle"],
        ["What intangible present can I give to my team?","@gdinwiddie"],
        ["How do you know where the boundaries of a story are?","@JohnMcFadyen"],
        ["What emotions are not allowed in your team?","@YvesHanoulle"],
        ["How can you change your workplace to improve your performance?","@JohnMcFadyen"],
        ["Why 'game' word is not acceptable in your office?","@didierkoc"],
        ["What makes you feel better today?","@didierkoc"],
        ["Some bands are together for 30 years. What keeps them together?","@didierkoc"],
        ["What question did we not ask ourselves that we should have?","@gdinwiddie"],
        ["What benefits have you found deliberate practice has given you?","@JohnMcFadyen"],
        ["What can you change this week to make your codebase more sustainable?","@OlafLewitz"],
        ["What do you dream for the future?","@gdinwiddie"],
        ["If you work on a project, what do you do about the friction?","@johannarothman"],
        ["Where are borders of your working environment?","@didierkoc"],
        ["How do you know you should leave a team/client and let someone else continue?","@OlafLewitz"],
        ["What is your favorite song, what could you learn from it?","@YvesHanoulle"],
        ["What is the last book you have read, and what idea out of it are you using know?","@YvesHanoulle"],
        ["What is the first question you should ask on joining a team?","@JohnMcFadyen"],
        ["What drives you/your team?","@YvesHanoulle"],
        ["How can a team help a new member?","@JohnMcFadyen"],
        ["If you would coach yourself what would you say?","@YvesHanoulle"],
        ["What made you ashamed of yourself today?","@YvesHanoulle"],
        ["Why did you start in your industry? Is this still valid? What are you doing to achieve this? ","@YvesHanoulle"],
        ["What will you do today to improve?","@JohnMcFadyen"],
        ["Where is your team wasting most of it's time on?","@YvesHanoulle"],
        ["What were you doing 5 years ago? What will you do 5 years from now?","@gdinwiddie"],
        ["How do you feel? How do you feel about that feeling?","@JerryWeinberg"],
        ["What are the critical success factors of your team?","@YvesHanoulle"],
        ["Can you talk about the bad things in your company?","@YvesHanoulle"],
        ["What would be the advantage for your customers if they would not use your software/services?","@YvesHanoulle"],
        ["What was the first thing you thoughed about today?","@YvesHanoulle"],
        ["How does your team help your company to achieve it's goals?","@YvesHanoulle"],
        ["What was the biggest roadblock for your current project, how did you remove it?","@YvesHanoulle"],
        ["What is the biggest adventure you can invent today?","@YvesHanoulle"],
        ["What tool could you do without?","@YvesHanoulle"],
        ["What would your partner say when she/he was on your current team?","@YvesHanoulle"],
        ["Think of the person who annoyed you most, today. What did they do well?","@gdinwiddie"],
        ["Why?Why?Why?Why?Why? Why?...","@YvesHanoulle"],
        ["Why not?","@YvesHanoulle"],
        ["Who helped you reach where you are now?","@gdinwiddie"],
        ["What is the biggest commitment you can make on your project?","@YvesHanoulle"],
        ["What would you say are the greatest challenges to Agile Coaching today?","@mheusser"],
        ["Have you used the Agile Retroflection of the Day questions? Tell us how...","@YvesHanoulle"],
        ["How do you recognise your own shortcomings?","@JohnMcFadyen"],
        ["What is the smallest thing you can do on your project to move it forward?","@YvesHanoulle"],
        ["Who is missing from your conversations?'","@deborahh"],
        ["What can you do today to help your team succeed?","@YvesHanoulle"],
        ["What made you proud of yourself today?","@YvesHanoulle"],
        ["Why are you going to work today?","@didierkoc"],
        ["What would your best friend say of he was coaching your team?","@YvesHanoulle"],
        ["Why are you 'going Agile'?","@JohnMcFadyen"],
        ["Where do you normally not look?","@DianaOfPortland"],
        ["When was the last time emotions where used in a good way in your team?","@YvesHanoulle"],
        ["What is the worst thing that could happen to you? Why is it bad? What would you learn from it?","@YvesHanoulle"],
        ["What would your team do without you? What would you do without your team?","@YvesHanoulle"],
        ["What have your learned from your current team that you would do with your new team?","Els Ryssen"],
        ["What have you learned from the last books you read?","@YvesHanoulle"],
        ["Where is your power to fight with daily problems coming from?","@didierkoc"],
        ["What would a 2 year old say when he was coaching your team?","@YvesHanoulle"],
        ["What is the point of your story?","@didierkoc"],
        ["Consider your most profound learning experience. where were you? what came just before and just after? When did you realize it was profound?","@YvesHanoulle"],
        ["Which workschedule do you tend to use to have an optimal workload?","@nomadzu"],
        ["Who sets the rules of what you are doing? #AROTD @YvesHanoulle","@YvesHanoulle"],
        ["What did you recognize during today's meeting?","@didierkoc"],
        ["Who wants you to succeed?","@deborahh"],
        ["With who of your (extended) team (collegues + clients) did you go to dinner recently?","@YvesHanoulle"],
        ["What is the most important idea found during retrospective?","@didierkoc"],
        ["What have you achieved today?","@YvesHanoulle"],
        ["How can the critic be of help to you?","@deborahh"],
        ["What is the next step in solving your current issue?","@YvesHanoulle"],
        ["Did you smile today?","@didierkoc"],
        ["How will you surprise your wife on March 8th?","@didierkoc"],
        ["What is the long term goal of your team?","@YvesHanoulle"],
        ["When was the last time you said sorry ?","@YvesHanoulle"],
        ["What skills that you learned from raising kids could you use (more) in your work? ","@YvesHanoulle"],
        ["How long it took you to understand agile differences?","@didierkoc"],
        ["Do you burn your work down or add value to result?","@didierkoc"],
        ["What time of the day is your Ideal Hour?","@didierkoc"],
        ["What are you doing to get out of your conformt zone?","@YvesHanoulle"],
        ["What are the external influences on your team?","@JohnMcFadyen"],
        ["How can you make your life more in balance? ","@YvesHanoulle"],
        ["What is your favorite card?","@didierkoc"],
        ["In what mental boxes have you put others lately? What was limiting about these definitions?","@YvesHanoulle"],
        ["Are you listen to your Pomodoro timer?","@didierkoc"],
        ["What keeps you humble?","@deborahh"],
        ["When was the last time you had fun at a meeting?","@YvesHanoulle"],
        ["Is your crew on board with you if boat is sinking?","@didierkoc"],
        ["50% of people are below average, how do you ensure you aren't one of them?","@JohnMcFadyen"],
        ["Which book would you like to reread? Why?","@YvesHanoulle"],
        ["How are you making impossible possible?","@didierkoc"],
        ["What did you learn from the mistakes you made today?","@YvesHanoulle"],
        ["How are you looking for feedback on your performance? (You == Person, Team, Company )","@mhsutton"],
        ["In what mental boxes did you put yourself today? What is limiting about those boxes?","@YvesHanoulle"],
        ["Did you manage to complete your action from the last retrospective? Why?","@JohnMcFadyen"],
        ["What assumptions have you exposed lately?","@YvesHanoulle"],
        ["How many new things you tried this week did not work out?","@YvesHanoulle"],
        ["Are you still in agile trenches?","@didierkoc"],
        ["With who in your team should you talk more?","@JohnMcFadyen"],
        ["How does your Team Spirit looks like?","@didierkoc"],
        ["Who can you pair with today?","@JohnMcFadyen"],
        ["Act as though you had just been newly appointed to your job. What would you do differently if you were coming in to your business without preconceived notions and with a completely fresh perspective?","@YvesHanoulle"],
        ["Which of  your features makes you smile proudly?","@didierkoc"],
        ["What could you do know that would bring you most joy?","@YvesHanoulle"],
        ["What makes you get up in the morning?","@YvesHanoulle"],
        ["Does your taskboard radiate usefull information?","@didierkoc"],
        ["What do you want ?","@ToF_"],
        ["Why do you like your collegues?","@YvesHanoulle"],
        ["What if you used different words?","@deborahh"],
        ["Is what you are working on, on your taskboard?","@YvesHanoulle"],
        ["How do you keep your comfort zone safe?","@JohnMcFadyen"],
        ["What is the long term advantage of the thing you are worring about? ","@YvesHanoulle"],
        ["When was the last time you were *ASTONISHED* ","@John_Gram"],
        ["When was the last time you've been titled 'crazy'? Long ago?","@martinheider"],
        ["What action you discussed in your retrospective can you focus on now?","@YvesHanoulle"],
        ["What did you learn yesterday?","@JohnMcFadyen"],
        ["How often did you worked overtime the last month? Why?","@martinheider"],
        ["Are you responding to change or following a plan?","@YvesHanoulle"],
        ["Are you scrum Master or scrum Shield?","@didierkoc"],
        ["What was the last win win win situation you created?","@YvesHanoulle"],
        ["Is your taskboard 2D or 3D with people standing in front of it?","@didierkoc"],
        ["Which of your roles have you been neglecting?","@YvesHanoulle"],
        ["What is smart, after all","@ToF_"],
        ["Just imagine, ... they are right and you are wrong? What would your next step be? ","@YvesHanoulle"],
        ["What can you take away to improve your process?","@JohnMcFadyen"],
        ["Are you procastinating of waiting for the last responsible moment?","@YvesHanoulle"],
        ["If a dictator would be part of your project, what would he say?","@YvesHanoulle"],
        ["When your tomorrow will become today?","@didierkoc"],
        ["What have you got rid of in the last iteration?","@martinheider"],
        ["What do you hope to learn today?","@JohnMcFadyen"],
        ["When was the last time you were surprised?","@YvesHanoulle"],
        ["How do you feel after retrospective? ","@didierkoc"],
        ["When did you last leave your comfort zone?","@JohnMcFadyen"],
        ["How can YOU make things worse?","@YvesHanoulle"],
        ["What is stopping you from learning?","@JohnMcFadyen"],
        ["How did your team cope with their last crisis?","@JohnMcFadyen"],
        ["How have you helped others learn today?","@JohnMcFadyen"],
        ["Do you care more about working software or about comprehensive documentation?","@YvesHanoulle"],
        ["What should you avoid doing in the future?","@JohnMcFadyen"],
        ["How have you been improving yourself this year?","@YvesHanoulle"],
        ["How is your team constrained?","@JohnMcFadyen"],
        ["Stop Think, is this what you want to do right now?","@YvesHanoulle"],
        ["Are you Scrum Maestro?","@didierkoc"],
        ["Who likes to do that thing you just hate to do?","@deborahh"],
        ["Are you sprinting or strolling?","@OlafLewitz"],
        ["Are you acting on Individuals and interactions or on processes and tools?","@YvesHanoulle"],
        ["What actions did you not take in the retrospective? ","@YvesHanoulle"],
        ["How do you stop those working at a distance becoming isolated?","@JohnMcFadyen"],
        ["Who should you thank right now?","@YvesHanoulle"],
        ["Who wants you to succeed? How can they help you?","@deborahh"],
        ["Who of your collegues makes you proud?","@YvesHanoulle"],
        ["Does change at your workplace rely more on a process or more on people ?","@ToF_"],
        ["What would you do if today was the last day before a release?","@YvesHanoulle"],
        ["Your next release has no bugs. What did you change to achieve that?","@OlafLewitz"],
        ["What inspired you to go into this industry? What inspires you today?","@YvesHanoulle"],
        ["What constraint should be removed from your team? Why?","@JohnMcFadyen"],
        ["When was the last time you listened to your gut feeling?","@YvesHanoulle"],
        ["How does the team recognise each others contributions?","@JohnMcFadyen"],
        ["What would *you* like to see happen?","@deborahh"],
        ["What actions did you take in your last retrospective? When have you started doing them?","@YvesHanoulle"],
        ["Are you an Agile island? How can you build bridges to others?","@JohnMcFadyen"],
        ["Are you collaborating or negotiating with your customer?","@YvesHanoulle"],
        ["How do you turn this situation in a win win one?","@YvesHanoulle"],
        ["Is your team closer during crises?","@didierkoc"],
        ["Are you a Product owner or a secretary?","@YvesHanoulle"],
        ["What have you done today to bring you closer to happiness?","@YvesHanoulle"],
        ["Are you practicing openness?","@didierkoc"],
        ["Who is 'management'","@YvesHanoulle"],
        ["Do you understand the contraints placed on your team? Do you understand why?","@JohnMcFadyen"],
        ["Is your inner coach Male or Female? Why?","@YvesHanoulle"],
        ["Does your progress line make you happy?","@didierkoc"],
        ["Who do you want to succeed? How can you help them?","@JohnMcFadyen"],
        ["How do you know when to start your first iteration","@DavidHussman"],
        ["What is giving you energy these days ? What is giving your team energy ?","@ToF_"],
        ["Is it road or tunnel between you and your colleague?","@didierkoc"],
        ["What would happen if you stopped thinking and start trying?","@YvesHanoulle"],
        ["When did you meet agile soul the last time?","@didierkoc"],
        ["Remember a peak experience of effective change in your life; in your work; does the comparison bring new insight ?","@ToF_"],
        ["who do you need to be for that to happen?","@deborahh"],
        ["Is your team The Organism?","@didierkoc"],
        ["What does your gut say?","@deborahh"],
        ["Does Scrum kill you or you kill Scrum?","@didierkoc"],
        ["What relationship do you want to have with your teammates ? Your collaborators ? Your customers ?","@ToF_"],
        ["What is the essence of synergy for you?","@YvesHanoulle"],
        ["What skill could you improve to benefit the team?","@deborahh"],
        ["With who do you want to spend some on-to-one?","@YvesHanoulle"],
        ["Why do you analyse stories? for estimation, to see what needs to be done? other?","@JohnMcFadyen"],
        ["What would the 'barely sufficient' solution look like in this situation?","@deborahh"],
        ["Do you act or are you being acted upon","@YvesHanoulle"],
        ["When is absence better than participation?","@didierkoc"],
        ["Think soft, feel hard","@YvesHanoulle"],
        ["When have you last said no to management successfully?","@OlafLewitz"],
        ["Who of your customers could you call today?","@YvesHanoulle"],
        ["Is courage alive in your team?","@didierkoc"],
        ["Define hapiness for you...","@YvesHanoulle"],
        ["Is self-organization self-myth?","@didierkoc"],
        ["Is Mr. Someone the performer in your team?","@didierkoc"],
        ["How would you explain your job to a 5 year old?","@YvesHanoulle"],
        ["When product owner surprised you by acceptation?","@didierkoc"],
        ["What is the most frustrating moment in the day?","@YvesHanoulle"],
        ["Are you saying 'stabilizing' or 'failing'?","@didierkoc"],
        ["What could make your week the most horible week?","@YvesHanoulle"],
        ["Are you sure personas will be happy to use a new feature?","@didierkoc"],
        ["What is the biggest waste in your job?","@YvesHanoulle"],
        ["Has your story The User?","@didierkoc"],
        ["How would you sell your job to someone else?","@YvesHanoulle"],
        ["Does your boss understand your agile status report?","@didierkoc"],
        ["How is your week planned?","@YvesHanoulle"],
        ["Describe a beautifull day on your project","@YvesHanoulle"],
        ["Did not you forget to rest between sprints?","@didierkoc"],
        ["Is you rproject on the highway to hell or on the stairway to heaven?","@YvesHanoulle"],
        ["Do you more score or loose?","@didierkoc"],
        ["What problems can you remove?","@YvesHanoulle"],
        ["Do you like to work on Must, Should, Could or Nice to have?","@didierkoc"],
        ["Can the project live with or without you?","@YvesHanoulle"],
        ["Are THEY a reason for all your problems?","@didierkoc"],
        ["How do you rely on your teammates ? Did you tell them ?","@ToF_"],
        ["How do you ensure you go to work happy and leave even happier?","@OlafLewitz"],
        ["Does frustration motive or kill?","@didierkoc"],
        ["If you don't have time to write defect-free code did you really have enough time to write it?","@flowchainsensei"],
        ["How do you know when you are Done?","@JohnMcFadyen"],
        ["Do you really understand the problem?","@YvesHanoulle"],
        ["Are you positively tired after your meeting?","@didierkoc"],
        ["Who is in your focus of Influence?","@YvesHanoulle"],
        ["Does your Product Owner understand business value? Not only ROI, but all aspects.","@JohnMcFadyen"],
        ["How do you show you care for your physical body?","@YvesHanoulle"],
        ["How to not hate a product manager?","@didierkoc"],
        ["Do you understand your burn down chart?","@didierkoc"],
        ["How do you know you are doing better?","@didierkoc"],
        ["When writing a story, do you think like a user or think like a customer?","@OlafLewitz"],
        ["Did you as a team remove someone from your team?","@didierkoc"],
        ["How do you overcome your organisation's practice of individual incentives?","@OlafLewitz"],
        ["How good do you know your programming pair?","@didierkoc"],
        ["How do you motivate the team to actually sprint?","@OlafLewitz"],
        ["Are you afraid of the second failure like the second car accident?","@didierkoc"],
        ["what is of low value and wasting precious time?","@deborahh"],
        ["Would you hire yourself?","@didierkoc"],
        ["Imagine they are right.  ","@YvesHanoulle"],
        ["Is there something absolutely great about your teammate that he/she doesn't seem to know about ?","@ToF_"],
        ["How do you balance creating business value against mitigating technical risks when prioritising your backlog?","@OlafLewitz"],
        ["How you know how much enough is enough?","@didierkoc"],
        ["As a coach, how do you know you can't help the team to improve anymore? When do you leave?","@OlafLewitz"],
        ["Are you full of endorphin after conference? How will you use it?","@didierkoc"],
        ["Name one of your big qualities","@YvesHanoulle"],
        ["Is your customer the driver?","@didierkoc"],
        ["How do you discern between your users' needs and what they say they need?","@OlafLewitz"],
        ["What would happen if you won't show up at work today?","@YvesHanoulle"],
        ["Will you kill a death sprint?","@didierkoc"],
        ["How many times have you told your partner you love him/her in the last hour?","@YvesHanoulle"],
        ["In your org, is 'Quality' seen as making an economic contribution to the business, or just one more cost of doing business?","@flowchainsensei"],
        ["As an architect, do you seek an agile architect position or do you find a new metaphor for what you do?","@OlafLewitz"],
        ["Is the value of what you are working on understood?","@JohnMcFadyen"],
        ["Which questions are answered in your backlog?","@didierkoc"],
        ["How do you as a team react in the face of blaming, complaining or rescueing ?","@ToF_"],
        ["How often do you change perspectives when you struggle with a problem?","@OlafLewitz"],
        ["What your yesterday's wheater says?","@didierkoc"],
        ["Are you Fooled by Randomness or rather Blinded by Certainty?","@OlafLewitz"]]

